### ISSUE TITLE
Refcursor support for Node.js

### ISSUE THREAD

**Issue by nguruyeshwanth** [brianc/node-pg-cursor#18]
Hello,

I am trying to call a stored proc from node which returns a refcursor, ideally I would like to FETCH ALL from the refcursor and utilize that result set for my front end dashboard data population.

Please let me know if this feature is supported and/or if there are any other packages that offer this functionality.

Regards,
Guru

**Comment by brianc** [comment]
Hey @nguruyeshwanth - sorry I missed your original question. Do you have code to demonstrate this issue? I'm going to close this out assuming you found an answer, but if not feel free to repopen it.
