### ISSUE TITLE
Access to result fields

### ISSUE THREAD

**Issue by sberan** [brianc/node-pg-cursor#22]
Currently, the only publicly available API for Cursor data is `Cursor#read`, which returns the rows read. For my application, I need access to the column information in the result set which is only (as far as I can tell) available via the private property `_result.fields`. Could fields be exposed somehow exposed via the `Cursor` API? I realize that there is some tricky timing involved so I'm very flexible on how this is exposed. Would you accept a PR for this change?

**Comment by brianc** [comment]
yeah I would definitely accept a PR for the change.  I think the best way to keep API compatibility would just be to have the full result object passed as a 3rd argument to the read callback: `read((err, rows, result) => { }` - does that sound good?  Then it's available always & backwards compatible.

**Comment by sberan** [comment]
▶️ see pr: #23
