### ISSUE TITLE
Uncaught exception calling cursor.close() on exhausted cursor using pool connection

### ISSUE THREAD

**Issue by rickbergfalk** [brianc/node-pg-cursor#27]
Hi @brianc 

Not sure if I'm using pg cursor incorrectly with pg pool or if I discovered a valid edge case. 

It seems that calling cursor.close on an exhausted cursor using a pool connection results in an uncaught TypeError exception within the pg module. What is strange about this is that it only seems to happen when the pool is saturated with other queries? Calling cursor.close on an exhausted cursor using a connection from a single-connection pool does not seem to experience the issue.

I've gone ahead and created some tests that showcase this behavior in #26 .

If the error is due to incorrect use of the 2 modules together, or if they are simply not compatible let me know and I'll close this issue and related pr.

Thanks for all your work on node-pg things!

**Comment by brianc** [comment]
They _should_ be compatible! pg-pool@2.0 changed some things which might have accidentally jostled this library.  Thanks so much for the tests! I'll pull it down & have a look right now.
