### ISSUE TITLE
cursor detail

### ISSUE THREAD

**Issue by ajayashuba** [brianc/node-pg-cursor#43]
can you throw some light on how cursor works here ? In my usecase i have some 100 million rows over which i need to process and order by a column .. so my query is ,will that happen everytime when i fetch next row of cursor or postgres uses some temporary table to store that processed data

**Comment by mikl** [comment]
Try reading the [PostgreSQL cursor documentation](https://www.postgresql.org/docs/current/plpgsql-cursors.html).
