### ISSUE TITLE
Cursor rewind support?

### ISSUE THREAD

**Issue by rkaw92** [brianc/node-pg-cursor#8]
Hi,

Is this module at all related to http://www.postgresql.org/docs/9.1/static/plpgsql-cursors.html ?
(i.e. is the OPEN ... mechanism used under the hood at all?)
I could not really see any query text in this module.

If so, it seems there ought to be some API for moving through the results - rewind, move forward, etc.

**Comment by brianc** [comment]
Hi @rkaw92 - this module actually doesn't use queries to manipulate or create cursors. The binary protocol has built-in support for cursor creation and access.  The protocol does _not_ support rewinding or skipping rows though...so it can't happen in this module.  I think there's probably room for a module that does it on the text level for more control, but that ain't a possibility here!  Hope this helps bring some clarity. :)
