### ISSUE TITLE
error: cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by rickbergfalk** [brianc/node-pg-cursor#9]
Hi Brian -

Would it be possible for this module to support multiple commands? Currently multiple-statement query text throws an error. 

Here's a little test code snippet I was trying to get working with no luck:

```js
  it('handles multiple commands', function(done) {
    var sql = "CREATE TEMPORARY TABLE temptable (word VARCHAR(10)); "
            + "INSERT INTO temptable (word) VALUES ('one'),('two'),('three'); "
            + "SELECT * FROM temptable; "
    var cursor = this.pgCursor(sql)
    cursor.read(10, function(err, res) {
      assert.ifError(err)
      assert.equal(res.length, 3)
      done()
    })
  })
```

Thanks for all your work on node-postgres!

**Comment by adeperio** [comment]
Also love to see a fix for this? Is there any word on this or a work around?

**Comment by brianc** [comment]
The postgres protocol only allows a cursor to be created & executed with a prepared statement. A prepared statement in postgres can contain at most one statement. So...it's actually impossible to allow multiple statements to create a cursor at the protocol level.  Sorry about that!

**Comment by calvintennant** [comment]
I worked around this limitation by using `pg-promise`, `pgp.as.format(query, values)` to format the string. 

`new Cursor(pgp.as.format('SELECT $1 FROM $2~ WHERE $3~ = $4', ['user', 'comment', 'type', 'article']))`
